import type { Product, Campaign, AdSet, Ad, Image, Job, Experiment, PerformanceNote } from "@shared/schema";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "PalmAura",
    description: "Premium magnesium lotion for deep relaxation and better sleep. Absorbs quickly, no greasy residue.",
    category: "Topicals",
    imageUrl: null,
    status: "active",
  },
  {
    id: 2,
    name: "FlexiGrip",
    description: "Joint and mobility support gummies with glucosamine, turmeric, and boswellia.",
    category: "Supplements",
    imageUrl: null,
    status: "active",
  },
  {
    id: 3,
    name: "ZenBrew",
    description: "Adaptogenic mushroom coffee blend with lion's mane, reishi, and chaga for calm focus.",
    category: "Beverages",
    imageUrl: null,
    status: "active",
  },
];

export const mockCampaigns: Campaign[] = [
  {
    id: 1,
    name: "PalmAura Spring Launch",
    productId: 1,
    objective: "conversions",
    offer: "Buy 2 Get 1 Free",
    targetAudience: "Women 28-45, wellness-focused, poor sleep quality",
    budget: 15000,
    startDate: "2026-01-15",
    endDate: "2026-03-15",
    status: "active",
    spend: 8420.50,
    roas: 3.2,
    cac: 24.80,
    ctr: 2.8,
    cvr: 4.1,
    notes: "Strong performance in first 3 weeks. Hook variants driving CTR lift.",
    createdAt: new Date("2026-01-10"),
  },
  {
    id: 2,
    name: "FlexiGrip Pain Point Angles",
    productId: 2,
    objective: "conversions",
    offer: "20% Off First Order",
    targetAudience: "Adults 35-60, active lifestyle, joint discomfort",
    budget: 10000,
    startDate: "2026-01-20",
    endDate: "2026-02-28",
    status: "active",
    spend: 5230.00,
    roas: 2.7,
    cac: 31.50,
    ctr: 2.1,
    cvr: 3.4,
    notes: "Testing new pain-point hooks. Need more UGC-style creatives.",
    createdAt: new Date("2026-01-18"),
  },
  {
    id: 3,
    name: "ZenBrew Morning Ritual",
    productId: 3,
    objective: "awareness",
    offer: "Free Sample Pack",
    targetAudience: "Professionals 25-40, coffee drinkers, productivity-focused",
    budget: 8000,
    startDate: "2026-02-01",
    endDate: "2026-03-01",
    status: "active",
    spend: 3100.00,
    roas: 1.9,
    cac: 38.20,
    ctr: 3.5,
    cvr: 2.2,
    notes: "Awareness phase. Morning routine angle resonating well.",
    createdAt: new Date("2026-01-28"),
  },
  {
    id: 4,
    name: "PalmAura Retargeting Q1",
    productId: 1,
    objective: "retargeting",
    offer: "15% Off + Free Shipping",
    targetAudience: "Site visitors, cart abandoners, past purchasers",
    budget: 5000,
    startDate: "2026-01-25",
    endDate: "2026-03-31",
    status: "paused",
    spend: 1850.00,
    roas: 4.8,
    cac: 12.40,
    ctr: 4.2,
    cvr: 7.5,
    notes: "Paused while restructuring audiences. Strong ROAS when active.",
    createdAt: new Date("2026-01-22"),
  },
  {
    id: 5,
    name: "FlexiGrip Influencer Whitelisting",
    productId: 2,
    objective: "conversions",
    offer: "Bundle Deal - 3 Month Supply",
    targetAudience: "Fitness enthusiasts 30-55, follow health influencers",
    budget: 12000,
    startDate: "2026-02-10",
    endDate: null,
    status: "draft",
    spend: 0,
    roas: null,
    cac: null,
    ctr: null,
    cvr: null,
    notes: "Pending influencer content delivery. Expected launch mid-Feb.",
    createdAt: new Date("2026-02-01"),
  },
];

export const mockAdSets: AdSet[] = [
  {
    id: 1,
    campaignId: 1,
    name: "Sleep Seekers - Problem Aware",
    avatarTarget: "Stressed professionals with poor sleep",
    awarenessLevel: "problem-aware",
    angle: "Sleep quality transformation",
    status: "active",
    budget: 5000,
  },
  {
    id: 2,
    campaignId: 1,
    name: "Wellness Moms - Solution Aware",
    avatarTarget: "Mothers 30-45 exploring natural remedies",
    awarenessLevel: "solution-aware",
    angle: "Natural magnesium benefits",
    status: "active",
    budget: 4000,
  },
  {
    id: 3,
    campaignId: 2,
    name: "Active Adults - Pain Points",
    avatarTarget: "Active adults with joint stiffness",
    awarenessLevel: "problem-aware",
    angle: "Pain relief without side effects",
    status: "active",
    budget: 3500,
  },
  {
    id: 4,
    campaignId: 2,
    name: "Athletes - Product Aware",
    avatarTarget: "Recreational athletes seeking recovery",
    awarenessLevel: "product-aware",
    angle: "Faster recovery, better performance",
    status: "active",
    budget: 3000,
  },
  {
    id: 5,
    campaignId: 3,
    name: "Coffee Lovers - Unaware",
    avatarTarget: "Daily coffee drinkers open to alternatives",
    awarenessLevel: "unaware",
    angle: "Upgrade your morning coffee",
    status: "active",
    budget: 3000,
  },
  {
    id: 6,
    campaignId: 3,
    name: "Biohackers - Most Aware",
    avatarTarget: "Health optimizers tracking nootropics",
    awarenessLevel: "most-aware",
    angle: "Cognitive performance stacking",
    status: "active",
    budget: 2500,
  },
  {
    id: 7,
    campaignId: 4,
    name: "Cart Abandoners",
    avatarTarget: "Users who added PalmAura to cart",
    awarenessLevel: "most-aware",
    angle: "Reminder with urgency",
    status: "paused",
    budget: 2500,
  },
  {
    id: 8,
    campaignId: 4,
    name: "Past Purchasers - Upsell",
    avatarTarget: "Previous PalmAura customers",
    awarenessLevel: "most-aware",
    angle: "Replenish and bundle",
    status: "paused",
    budget: 2500,
  },
];

export const mockAds: Ad[] = [
  {
    id: 1,
    adSetId: 1,
    campaignId: 1,
    name: "PalmAura - Sleep Hook v1",
    concept: "Before/after sleep tracking screenshot showing improvement after using PalmAura",
    headline: "Finally Sleep Through the Night",
    hook: "I tracked my sleep for 30 days after switching to magnesium lotion...",
    cta: "Shop Now",
    adType: "static-image",
    avatarTarget: "Stressed professionals with poor sleep",
    awarenessLevel: "problem-aware",
    angle: "Sleep quality transformation",
    visualMotif: "Dark bedroom, soft glow, sleep tracker",
    headlineType: "outcome-based",
    status: "winner",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create a calming bedroom scene with soft ambient lighting and a sleep tracker showing improved REM cycles",
    tags: ["sleep", "before-after", "data-driven", "testimonial"],
    spend: 2150.00,
    impressions: 85000,
    clicks: 2380,
    conversions: 98,
    ctr: 2.8,
    cvr: 4.1,
    roas: 4.2,
    whyItWon: "Combines social proof with data visualization. The sleep tracker screenshot adds credibility while the personal narrative creates emotional connection.",
    whenToReuse: "Launch campaigns targeting problem-aware audiences concerned about sleep. Works well in cold traffic with high-intent keywords.",
    whenNotToReuse: "Avoid for audiences already aware of magnesium benefits. The discovery angle loses impact with solution-aware segments.",
    isWinner: true,
    createdAt: new Date("2026-01-15"),
  },
  {
    id: 2,
    adSetId: 1,
    campaignId: 1,
    name: "PalmAura - Stress Relief UGC",
    concept: "UGC-style video of someone applying PalmAura before bed with voiceover about stress",
    headline: "The 30-Second Nighttime Ritual That Changed Everything",
    hook: "My therapist told me to try this before I reach for melatonin again",
    cta: "Try It Tonight",
    adType: "ugc-video",
    avatarTarget: "Stressed professionals with poor sleep",
    awarenessLevel: "problem-aware",
    angle: "Expert recommendation",
    visualMotif: "Warm bathroom lighting, product application close-up",
    headlineType: "curiosity-based",
    status: "testing",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: null,
    tags: ["ugc", "expert-rec", "nighttime-routine", "stress"],
    spend: 890.00,
    impressions: 35000,
    clicks: 980,
    conversions: 32,
    ctr: 2.8,
    cvr: 3.3,
    roas: 2.9,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-18"),
  },
  {
    id: 3,
    adSetId: 2,
    campaignId: 1,
    name: "PalmAura - Mom Life Hook",
    concept: "Split screen: chaotic mom life vs peaceful bedtime with PalmAura",
    headline: "When Mom Finally Gets Her Rest",
    hook: "5 kids. 0 hours of sleep. Until I found this lotion in my feed...",
    cta: "Get Yours",
    adType: "static-image",
    avatarTarget: "Mothers 30-45 exploring natural remedies",
    awarenessLevel: "solution-aware",
    angle: "Relatable mom struggle",
    visualMotif: "Split screen contrast, warm vs chaotic tones",
    headlineType: "identity-based",
    status: "approved",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create a split-screen image contrasting busy mom life with peaceful sleep scene",
    tags: ["mom-life", "relatable", "contrast", "identity"],
    spend: 450.00,
    impressions: 18000,
    clicks: 540,
    conversions: 22,
    ctr: 3.0,
    cvr: 4.1,
    roas: 3.5,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-20"),
  },
  {
    id: 4,
    adSetId: 2,
    campaignId: 1,
    name: "PalmAura - Ingredient Spotlight",
    concept: "Educational carousel about magnesium absorption through skin vs oral supplements",
    headline: "Why Your Magnesium Pills Aren't Working",
    hook: "Science says your body absorbs magnesium 3x faster through the skin",
    cta: "Learn More",
    adType: "carousel",
    avatarTarget: "Mothers 30-45 exploring natural remedies",
    awarenessLevel: "solution-aware",
    angle: "Scientific education",
    visualMotif: "Clean infographic style, molecule illustrations",
    headlineType: "challenge-based",
    status: "draft",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: null,
    tags: ["educational", "science", "ingredient", "carousel"],
    spend: 0,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    ctr: 0,
    cvr: 0,
    roas: 0,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-22"),
  },
  {
    id: 5,
    adSetId: 3,
    campaignId: 2,
    name: "FlexiGrip - Morning Stiffness",
    concept: "Person struggling to get out of bed due to joint stiffness, then moving freely after FlexiGrip",
    headline: "Stop Dreading Your Morning Stretch",
    hook: "If your joints sound like a bowl of cereal every morning, read this",
    cta: "Move Freely Again",
    adType: "static-image",
    avatarTarget: "Active adults with joint stiffness",
    awarenessLevel: "problem-aware",
    angle: "Morning stiffness pain point",
    visualMotif: "Sunrise, stretching silhouette, warm tones",
    headlineType: "empathy-based",
    status: "winner",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create image of person stretching freely at sunrise with warm golden lighting",
    tags: ["pain-point", "morning-routine", "mobility", "empathy"],
    spend: 1800.00,
    impressions: 72000,
    clicks: 1512,
    conversions: 51,
    ctr: 2.1,
    cvr: 3.4,
    roas: 3.8,
    whyItWon: "Relatable pain-point hook with vivid sensory language creates immediate recognition. The cereal metaphor is memorable and shareable.",
    whenToReuse: "Cold traffic campaigns targeting problem-aware audiences with joint issues. Morning routine contexts and wellness content placements.",
    whenNotToReuse: "Product-aware audiences who already know about glucosamine supplements. The humor may not land with more clinical/serious audiences.",
    isWinner: true,
    createdAt: new Date("2026-01-20"),
  },
  {
    id: 6,
    adSetId: 3,
    campaignId: 2,
    name: "FlexiGrip - Comparison Chart",
    concept: "Side-by-side comparison of FlexiGrip vs traditional glucosamine pills",
    headline: "Not All Joint Supplements Are Created Equal",
    hook: "I compared 12 joint supplements. Here is what I found.",
    cta: "See the Difference",
    adType: "static-image",
    avatarTarget: "Active adults with joint stiffness",
    awarenessLevel: "problem-aware",
    angle: "Comparison and social proof",
    visualMotif: "Clean comparison table, checkmarks, product imagery",
    headlineType: "authority-based",
    status: "generated",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create a clean comparison chart showing FlexiGrip advantages over generic supplements",
    tags: ["comparison", "authority", "data-driven", "infographic"],
    spend: 0,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    ctr: 0,
    cvr: 0,
    roas: 0,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-25"),
  },
  {
    id: 7,
    adSetId: 4,
    campaignId: 2,
    name: "FlexiGrip - Athlete Recovery",
    concept: "Athletic person using FlexiGrip as part of post-workout recovery stack",
    headline: "The Recovery Stack Pro Athletes Use",
    hook: "My physio recommended adding this to my post-workout routine",
    cta: "Recover Faster",
    adType: "ugc-video",
    avatarTarget: "Recreational athletes seeking recovery",
    awarenessLevel: "product-aware",
    angle: "Performance and recovery",
    visualMotif: "Gym setting, post-workout, product placement",
    headlineType: "authority-based",
    status: "testing",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: null,
    tags: ["athlete", "recovery", "performance", "ugc"],
    spend: 620.00,
    impressions: 24800,
    clicks: 620,
    conversions: 18,
    ctr: 2.5,
    cvr: 2.9,
    roas: 2.3,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-22"),
  },
  {
    id: 8,
    adSetId: 5,
    campaignId: 3,
    name: "ZenBrew - Coffee Swap",
    concept: "Person pouring out regular coffee and making ZenBrew with calm morning vibes",
    headline: "Your Coffee Is Stealing Your Focus",
    hook: "I quit coffee for 7 days and replaced it with this. The results shocked me.",
    cta: "Try ZenBrew",
    adType: "static-image",
    avatarTarget: "Daily coffee drinkers open to alternatives",
    awarenessLevel: "unaware",
    angle: "Coffee replacement disruption",
    visualMotif: "Peaceful morning kitchen, steaming mug, natural light",
    headlineType: "provocation-based",
    status: "approved",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create a serene morning kitchen scene with a steaming mug of mushroom coffee in natural light",
    tags: ["coffee-swap", "morning-routine", "disruption", "calm"],
    spend: 780.00,
    impressions: 31200,
    clicks: 1092,
    conversions: 24,
    ctr: 3.5,
    cvr: 2.2,
    roas: 1.9,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-02-01"),
  },
  {
    id: 9,
    adSetId: 5,
    campaignId: 3,
    name: "ZenBrew - Focus Stack",
    concept: "Productivity setup with ZenBrew as the centerpiece of a focus ritual",
    headline: "The Focus Drink Silicon Valley Won't Shut Up About",
    hook: "Every founder I know has switched from espresso to this adaptogenic blend",
    cta: "Get Focused",
    adType: "static-image",
    avatarTarget: "Daily coffee drinkers open to alternatives",
    awarenessLevel: "unaware",
    angle: "Social proof and exclusivity",
    visualMotif: "Minimal desk setup, laptop, ZenBrew mug, clean aesthetic",
    headlineType: "social-proof-based",
    status: "generated",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create a minimalist desk setup with mushroom coffee, laptop, and clean productivity aesthetic",
    tags: ["focus", "productivity", "social-proof", "tech"],
    spend: 0,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    ctr: 0,
    cvr: 0,
    roas: 0,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-02-02"),
  },
  {
    id: 10,
    adSetId: 6,
    campaignId: 3,
    name: "ZenBrew - Nootropic Stack",
    concept: "Educational breakdown of lion's mane and reishi benefits for cognitive function",
    headline: "The Science Behind Mushroom Coffee",
    hook: "3 peer-reviewed studies changed how I think about my morning brew",
    cta: "Read the Science",
    adType: "carousel",
    avatarTarget: "Health optimizers tracking nootropics",
    awarenessLevel: "most-aware",
    angle: "Scientific credibility",
    visualMotif: "Clean research paper style, mushroom close-ups, brain imagery",
    headlineType: "education-based",
    status: "draft",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: null,
    tags: ["nootropic", "science", "education", "mushroom"],
    spend: 0,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    ctr: 0,
    cvr: 0,
    roas: 0,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-02-03"),
  },
  {
    id: 11,
    adSetId: 7,
    campaignId: 4,
    name: "PalmAura - Cart Reminder",
    concept: "Simple reminder with product image and urgency messaging",
    headline: "You Left Something Behind",
    hook: "Your PalmAura is still in your cart, and stock is limited",
    cta: "Complete Your Order",
    adType: "static-image",
    avatarTarget: "Users who added PalmAura to cart",
    awarenessLevel: "most-aware",
    angle: "Cart abandonment urgency",
    visualMotif: "Product hero shot with subtle countdown element",
    headlineType: "urgency-based",
    status: "approved",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create a clean product hero shot of PalmAura lotion with urgency visual cues",
    tags: ["retargeting", "urgency", "cart-abandon", "direct"],
    spend: 320.00,
    impressions: 8500,
    clicks: 357,
    conversions: 28,
    ctr: 4.2,
    cvr: 7.8,
    roas: 5.1,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-25"),
  },
  {
    id: 12,
    adSetId: 8,
    campaignId: 4,
    name: "PalmAura - Repeat Purchase Bundle",
    concept: "Offer bundle deal to past customers showing their savings potential",
    headline: "Your Reorder + A Free Gift",
    hook: "Since you loved PalmAura, we made you a deal you can not refuse",
    cta: "Claim Your Bundle",
    adType: "static-image",
    avatarTarget: "Previous PalmAura customers",
    awarenessLevel: "most-aware",
    angle: "Loyalty and value",
    visualMotif: "Gift box opening, product bundle arrangement",
    headlineType: "offer-based",
    status: "retired",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create image of PalmAura product bundle with gift box aesthetic",
    tags: ["repeat-purchase", "loyalty", "bundle", "offer"],
    spend: 950.00,
    impressions: 15200,
    clicks: 608,
    conversions: 42,
    ctr: 4.0,
    cvr: 6.9,
    roas: 4.5,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-26"),
  },
  {
    id: 13,
    adSetId: 1,
    campaignId: 1,
    name: "PalmAura - ASMR Application",
    concept: "ASMR-style close-up of PalmAura being applied, focusing on texture and relaxation sounds",
    headline: "Feel the Calm",
    hook: "Turn your sound on. This is your new nighttime ritual.",
    cta: "Experience PalmAura",
    adType: "video",
    avatarTarget: "Stressed professionals with poor sleep",
    awarenessLevel: "problem-aware",
    angle: "Sensory experience",
    visualMotif: "Extreme close-up, soft lighting, ASMR aesthetic",
    headlineType: "sensory-based",
    status: "draft",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: null,
    tags: ["asmr", "sensory", "video", "relaxation"],
    spend: 0,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    ctr: 0,
    cvr: 0,
    roas: 0,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-02-04"),
  },
  {
    id: 14,
    adSetId: 3,
    campaignId: 2,
    name: "FlexiGrip - Gardening Angle",
    concept: "Older adult enjoying gardening pain-free thanks to FlexiGrip",
    headline: "Get Back to the Garden",
    hook: "My knees said no. FlexiGrip said yes. Now I am back doing what I love.",
    cta: "Move Without Limits",
    adType: "static-image",
    avatarTarget: "Active adults with joint stiffness",
    awarenessLevel: "problem-aware",
    angle: "Lifestyle activity restoration",
    visualMotif: "Sunny garden, kneeling comfortably, flowers",
    headlineType: "transformation-based",
    status: "generated",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create image of person happily gardening in sunlight, showing mobility and joy",
    tags: ["lifestyle", "gardening", "transformation", "relatable"],
    spend: 0,
    impressions: 0,
    clicks: 0,
    conversions: 0,
    ctr: 0,
    cvr: 0,
    roas: 0,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-02-03"),
  },
  {
    id: 15,
    adSetId: 6,
    campaignId: 3,
    name: "ZenBrew - Podcast Sponsor Style",
    concept: "Podcast-style ad read with text overlay mimicking a sponsor segment",
    headline: "This Episode Is Brought to You By Your Brain",
    hook: "If you have been listening to every biohacking podcast, you have heard about this",
    cta: "Stack Your Morning",
    adType: "static-image",
    avatarTarget: "Health optimizers tracking nootropics",
    awarenessLevel: "most-aware",
    angle: "Podcast culture and biohacking community",
    visualMotif: "Podcast setup, microphone, product placement",
    headlineType: "culture-based",
    status: "retired",
    imageUrl: null,
    thumbnailUrl: null,
    promptUsed: "Create a podcast studio setup with ZenBrew product placement near microphone",
    tags: ["podcast", "biohacking", "culture", "community"],
    spend: 1200.00,
    impressions: 48000,
    clicks: 960,
    conversions: 19,
    ctr: 2.0,
    cvr: 2.0,
    roas: 1.2,
    whyItWon: null,
    whenToReuse: null,
    whenNotToReuse: null,
    isWinner: false,
    createdAt: new Date("2026-01-28"),
  },
];

export const mockImages: Image[] = [
  {
    id: 1,
    adId: 1,
    experimentId: null,
    name: "PalmAura Sleep Tracker Visual",
    url: null,
    promptUsed: "Calming bedroom with sleep tracker showing improved REM cycles, soft ambient lighting",
    referenceImageUrl: null,
    variant: "A",
    status: "approved",
    tags: ["sleep", "bedroom", "tracker"],
    createdAt: new Date("2026-01-15"),
  },
  {
    id: 2,
    adId: 3,
    experimentId: null,
    name: "Mom Life Split Screen",
    url: null,
    promptUsed: "Split screen: chaotic family morning vs peaceful evening with magnesium lotion",
    referenceImageUrl: null,
    variant: "A",
    status: "approved",
    tags: ["mom", "split-screen", "contrast"],
    createdAt: new Date("2026-01-20"),
  },
  {
    id: 3,
    adId: 5,
    experimentId: 1,
    name: "Morning Stretch Sunrise",
    url: null,
    promptUsed: "Person stretching freely at sunrise, warm golden lighting, silhouette style",
    referenceImageUrl: null,
    variant: "A",
    status: "approved",
    tags: ["sunrise", "stretch", "mobility"],
    createdAt: new Date("2026-01-20"),
  },
  {
    id: 4,
    adId: 8,
    experimentId: 2,
    name: "ZenBrew Morning Kitchen",
    url: null,
    promptUsed: "Serene morning kitchen with steaming mushroom coffee mug, natural light",
    referenceImageUrl: null,
    variant: "A",
    status: "approved",
    tags: ["kitchen", "morning", "coffee"],
    createdAt: new Date("2026-02-01"),
  },
  {
    id: 5,
    adId: 9,
    experimentId: 2,
    name: "ZenBrew Desk Setup",
    url: null,
    promptUsed: "Minimalist desk setup with mushroom coffee, laptop, productivity aesthetic",
    referenceImageUrl: null,
    variant: "B",
    status: "generated",
    tags: ["desk", "productivity", "minimal"],
    createdAt: new Date("2026-02-02"),
  },
  {
    id: 6,
    adId: 14,
    experimentId: null,
    name: "FlexiGrip Gardening Joy",
    url: null,
    promptUsed: "Person happily gardening in sunlight, showing mobility and joy",
    referenceImageUrl: null,
    variant: "A",
    status: "generated",
    tags: ["gardening", "outdoors", "joy"],
    createdAt: new Date("2026-02-03"),
  },
];

export const mockJobs: Job[] = [
  {
    id: 1,
    name: "Generate PalmAura Sleep Visual",
    stage: "image-generation",
    status: "success",
    payload: { adId: 1, prompt: "Calming bedroom scene with sleep tracker" },
    output: { imageUrl: null, resolution: "1024x1024" },
    errorMessage: null,
    webhookUrl: null,
    duration: 12,
    retryCount: 0,
    relatedRecordId: "ad-1",
    startedAt: new Date("2026-01-15T10:00:00"),
    completedAt: new Date("2026-01-15T10:00:12"),
    createdAt: new Date("2026-01-15T10:00:00"),
  },
  {
    id: 2,
    name: "Generate FlexiGrip Comparison Chart",
    stage: "image-generation",
    status: "success",
    payload: { adId: 6, prompt: "Clean comparison chart for FlexiGrip" },
    output: { imageUrl: null, resolution: "1024x1024" },
    errorMessage: null,
    webhookUrl: null,
    duration: 15,
    retryCount: 0,
    relatedRecordId: "ad-6",
    startedAt: new Date("2026-01-25T14:00:00"),
    completedAt: new Date("2026-01-25T14:00:15"),
    createdAt: new Date("2026-01-25T14:00:00"),
  },
  {
    id: 3,
    name: "Copy Generation - ZenBrew Hooks",
    stage: "copy-generation",
    status: "success",
    payload: { campaignId: 3, count: 5 },
    output: { hooks: ["Hook 1", "Hook 2", "Hook 3", "Hook 4", "Hook 5"] },
    errorMessage: null,
    webhookUrl: null,
    duration: 8,
    retryCount: 0,
    relatedRecordId: "campaign-3",
    startedAt: new Date("2026-02-01T09:00:00"),
    completedAt: new Date("2026-02-01T09:00:08"),
    createdAt: new Date("2026-02-01T09:00:00"),
  },
  {
    id: 4,
    name: "Generate ZenBrew Morning Scene",
    stage: "image-generation",
    status: "running",
    payload: { adId: 8, prompt: "Serene morning kitchen with mushroom coffee" },
    output: null,
    errorMessage: null,
    webhookUrl: null,
    duration: null,
    retryCount: 0,
    relatedRecordId: "ad-8",
    startedAt: new Date("2026-02-06T08:30:00"),
    completedAt: null,
    createdAt: new Date("2026-02-06T08:30:00"),
  },
  {
    id: 5,
    name: "Audience Sync - PalmAura Lookalikes",
    stage: "audience-sync",
    status: "success",
    payload: { campaignId: 1, audienceType: "lookalike" },
    output: { synced: 15000, platform: "meta" },
    errorMessage: null,
    webhookUrl: null,
    duration: 45,
    retryCount: 0,
    relatedRecordId: "campaign-1",
    startedAt: new Date("2026-01-20T06:00:00"),
    completedAt: new Date("2026-01-20T06:00:45"),
    createdAt: new Date("2026-01-20T06:00:00"),
  },
  {
    id: 6,
    name: "Generate FlexiGrip Gardening Image",
    stage: "image-generation",
    status: "pending",
    payload: { adId: 14, prompt: "Happy gardening in sunlight" },
    output: null,
    errorMessage: null,
    webhookUrl: null,
    duration: null,
    retryCount: 0,
    relatedRecordId: "ad-14",
    startedAt: null,
    completedAt: null,
    createdAt: new Date("2026-02-06T09:00:00"),
  },
  {
    id: 7,
    name: "Copy Generation - PalmAura Headlines",
    stage: "copy-generation",
    status: "failed",
    payload: { campaignId: 1, count: 10, style: "emotional" },
    output: null,
    errorMessage: "Rate limit exceeded. Retry after 60 seconds.",
    webhookUrl: null,
    duration: 3,
    retryCount: 2,
    relatedRecordId: "campaign-1",
    startedAt: new Date("2026-02-05T16:00:00"),
    completedAt: new Date("2026-02-05T16:00:03"),
    createdAt: new Date("2026-02-05T16:00:00"),
  },
  {
    id: 8,
    name: "Performance Report - Weekly",
    stage: "reporting",
    status: "success",
    payload: { period: "2026-W05", campaigns: [1, 2, 3] },
    output: { reportUrl: null, metricsCount: 24 },
    errorMessage: null,
    webhookUrl: null,
    duration: 22,
    retryCount: 0,
    relatedRecordId: "report-w05",
    startedAt: new Date("2026-02-03T00:00:00"),
    completedAt: new Date("2026-02-03T00:00:22"),
    createdAt: new Date("2026-02-03T00:00:00"),
  },
  {
    id: 9,
    name: "A/B Test Analysis - Sleep Hooks",
    stage: "analysis",
    status: "success",
    payload: { experimentId: 1 },
    output: { winner: "variant-a", confidence: 0.95 },
    errorMessage: null,
    webhookUrl: null,
    duration: 5,
    retryCount: 0,
    relatedRecordId: "experiment-1",
    startedAt: new Date("2026-02-02T12:00:00"),
    completedAt: new Date("2026-02-02T12:00:05"),
    createdAt: new Date("2026-02-02T12:00:00"),
  },
  {
    id: 10,
    name: "Creative Resize - Multi-Platform",
    stage: "image-processing",
    status: "retrying",
    payload: { adIds: [1, 5], formats: ["1080x1080", "1080x1920", "1200x628"] },
    output: null,
    errorMessage: "Timeout on 1080x1920 format. Retrying.",
    webhookUrl: null,
    duration: null,
    retryCount: 1,
    relatedRecordId: "batch-resize-01",
    startedAt: new Date("2026-02-06T07:00:00"),
    completedAt: null,
    createdAt: new Date("2026-02-06T07:00:00"),
  },
  {
    id: 11,
    name: "Webhook - Shopify Order Sync",
    stage: "integration",
    status: "success",
    payload: { source: "shopify", event: "order.created" },
    output: { ordersProcessed: 47 },
    errorMessage: null,
    webhookUrl: "https://hooks.example.com/shopify",
    duration: 2,
    retryCount: 0,
    relatedRecordId: "integration-shopify",
    startedAt: new Date("2026-02-06T06:00:00"),
    completedAt: new Date("2026-02-06T06:00:02"),
    createdAt: new Date("2026-02-06T06:00:00"),
  },
  {
    id: 12,
    name: "Generate PalmAura ASMR Thumbnail",
    stage: "image-generation",
    status: "pending",
    payload: { adId: 13, prompt: "ASMR close-up of lotion application" },
    output: null,
    errorMessage: null,
    webhookUrl: null,
    duration: null,
    retryCount: 0,
    relatedRecordId: "ad-13",
    startedAt: null,
    completedAt: null,
    createdAt: new Date("2026-02-06T09:15:00"),
  },
];

export const mockExperiments: Experiment[] = [
  {
    id: 1,
    name: "PalmAura Sleep Hook Showdown",
    campaignId: 1,
    hypothesis: "Data-driven sleep tracker hook will outperform UGC testimonial hook in CTR and CVR for problem-aware audiences",
    primaryMetric: "CVR",
    status: "completed",
    variantAId: 1,
    variantBId: 2,
    variantCId: null,
    variantAName: "Sleep Tracker Data Hook",
    variantBName: "UGC Stress Relief Hook",
    variantCName: null,
    variantAResult: { ctr: 2.8, cvr: 4.1, roas: 4.2, spend: 2150, impressions: 85000, confidence: 0.95 },
    variantBResult: { ctr: 2.8, cvr: 3.3, roas: 2.9, spend: 890, impressions: 35000, confidence: 0.82 },
    variantCResult: null,
    winnerId: 1,
    winnerVariant: "A",
    notes: "Variant A (data hook) won with 95% confidence. Higher CVR despite similar CTR suggests the data visualization builds more trust at decision point.",
    createdAt: new Date("2026-01-18"),
  },
  {
    id: 2,
    name: "ZenBrew Awareness Angle Test",
    campaignId: 3,
    hypothesis: "Disruptive coffee-swap angle will generate higher CTR than productivity social proof angle for unaware audiences",
    primaryMetric: "CTR",
    status: "running",
    variantAId: 8,
    variantBId: 9,
    variantCId: null,
    variantAName: "Coffee Swap Disruption",
    variantBName: "Focus Stack Social Proof",
    variantCName: null,
    variantAResult: { ctr: 3.5, cvr: 2.2, roas: 1.9, spend: 780, impressions: 31200, confidence: 0.71 },
    variantBResult: { ctr: 2.8, cvr: 1.8, roas: 1.4, spend: 420, impressions: 15000, confidence: 0.65 },
    variantCResult: null,
    winnerId: null,
    winnerVariant: null,
    notes: "Early data favoring Variant A but not yet statistically significant. Need 2 more weeks of data.",
    createdAt: new Date("2026-02-01"),
  },
  {
    id: 3,
    name: "FlexiGrip Creative Format Test",
    campaignId: 2,
    hypothesis: "Static empathy-based image will outperform UGC video for problem-aware joint pain audiences on CTR",
    primaryMetric: "CTR",
    status: "running",
    variantAId: 5,
    variantBId: 7,
    variantCId: 6,
    variantAName: "Static Morning Stiffness",
    variantBName: "UGC Athlete Recovery",
    variantCName: "Static Comparison Chart",
    variantAResult: { ctr: 2.1, cvr: 3.4, roas: 3.8, spend: 1800, impressions: 72000, confidence: 0.88 },
    variantBResult: { ctr: 2.5, cvr: 2.9, roas: 2.3, spend: 620, impressions: 24800, confidence: 0.72 },
    variantCResult: { ctr: 1.6, cvr: 2.1, roas: 1.7, spend: 310, impressions: 19375, confidence: 0.55 },
    winnerId: null,
    winnerVariant: null,
    notes: "Variant A leading in ROAS and CVR. Variant B has higher CTR but lower conversion. Variant C underperforming. May call early for A.",
    createdAt: new Date("2026-01-22"),
  },
  {
    id: 4,
    name: "PalmAura Mom vs Sleep Angle",
    campaignId: 1,
    hypothesis: "Identity-based mom angle will outperform generic sleep angle for solution-aware female audiences in CVR",
    primaryMetric: "CVR",
    status: "draft",
    variantAId: 3,
    variantBId: null,
    variantCId: null,
    variantAName: "Mom Life Hook",
    variantBName: null,
    variantCName: null,
    variantAResult: null,
    variantBResult: null,
    variantCResult: null,
    winnerId: null,
    winnerVariant: null,
    notes: "Waiting for Variant B creative to be generated. Need a generic sleep angle creative for comparison.",
    createdAt: new Date("2026-02-04"),
  },
];

export const mockPerformanceNotes: PerformanceNote[] = [
  {
    id: 1,
    metricName: "Spend",
    value: 16750.50,
    period: "2026-W05",
    notes: "Total ad spend across all active campaigns. Trending 8% above weekly target.",
    source: "Meta Ads Manager",
    createdAt: new Date("2026-02-03"),
  },
  {
    id: 2,
    metricName: "ROAS",
    value: 2.94,
    period: "2026-W05",
    notes: "Blended ROAS across all campaigns. PalmAura pulling average up, ZenBrew dragging it down slightly.",
    source: "Meta Ads Manager",
    createdAt: new Date("2026-02-03"),
  },
  {
    id: 3,
    metricName: "CAC",
    value: 28.40,
    period: "2026-W05",
    notes: "Blended customer acquisition cost. Target is under $30. PalmAura retargeting keeping average healthy.",
    source: "Shopify + Meta",
    createdAt: new Date("2026-02-03"),
  },
  {
    id: 4,
    metricName: "CTR",
    value: 2.82,
    period: "2026-W05",
    notes: "Average click-through rate. ZenBrew morning ritual content driving highest CTR at 3.5%.",
    source: "Meta Ads Manager",
    createdAt: new Date("2026-02-03"),
  },
  {
    id: 5,
    metricName: "CVR",
    value: 3.72,
    period: "2026-W05",
    notes: "Blended conversion rate from click to purchase. Retargeting campaigns significantly above average.",
    source: "Shopify",
    createdAt: new Date("2026-02-03"),
  },
  {
    id: 6,
    metricName: "AOV",
    value: 67.50,
    period: "2026-W05",
    notes: "Average order value. Bundle offers on PalmAura and FlexiGrip pushing AOV above $65 target.",
    source: "Shopify",
    createdAt: new Date("2026-02-03"),
  },
];
